global:
  resolve_timeout: 20s

route:
  group_wait: 0s
  receiver: 'admin'

receivers:
  - name: 'admin'
    email_configs:
    - to: mizterbasoo@gmail.com
      from: mizterbasoo@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: mizterbasoo@gmail.com
      auth_identity: mizterbasoo@gmail.com
      auth_password: fjrtvsxxxmgsdiju
      send_resolved: false
    webhook_configs:
    - url: 'http://10.15.11.106:5000/alert'
      send_resolved: false
